## Get data

In [13]:
import json
import pandas as pd

import aiohttp

from understat import Understat
import json


async with aiohttp.ClientSession() as session:
    understat = Understat(session)
    fixtures =  await understat.get_league_results("epl",2023)
    print(fixtures[:2])

[{'id': '22275', 'isResult': True, 'h': {'id': '92', 'title': 'Burnley', 'short_title': 'BUR'}, 'a': {'id': '88', 'title': 'Manchester City', 'short_title': 'MCI'}, 'goals': {'h': '0', 'a': '3'}, 'xG': {'h': '0.311032', 'a': '2.40074'}, 'datetime': '2023-08-11 19:00:00', 'forecast': {'w': '0.0177', 'd': '0.0854', 'l': '0.8969'}}, {'id': '22276', 'isResult': True, 'h': {'id': '83', 'title': 'Arsenal', 'short_title': 'ARS'}, 'a': {'id': '249', 'title': 'Nottingham Forest', 'short_title': 'NOT'}, 'goals': {'h': '2', 'a': '1'}, 'xG': {'h': '0.84262', 'a': '0.966305'}, 'datetime': '2023-08-12 11:30:00', 'forecast': {'w': '0.2797', 'd': '0.3363', 'l': '0.384'}}]

## Clean data

In [5]:
import pandas as pd

result_dict_list = []

for item in fixtures:
  result_dict = {
    'home_team': item['h']['title'],
    'away_teaam': item['a']['title'],
    'home_goals': item['goals']['h'],
    'away_goals': item['goals']['a'],
    'home_xG': item['xG']['h'],
    'away_xG': item['xG']['a'],
  }
  result_dict_list.append(result_dict)

pd.DataFrame(result_dict_list)

       home_team         away_teaam home_goals away_goals   home_xG   away_xG
0        Burnley    Manchester City          0          3  0.311032   2.40074
1        Arsenal  Nottingham Forest          2          1   0.84262  0.966305
2    Bournemouth           West Ham          1          1   1.51025    1.4834
3       Brighton              Luton          4          1   4.36748   1.88594
4        Everton             Fulham          0          1   2.59001   1.58144
..           ...                ...        ...        ...       ...       ...
272      Arsenal          Brentford          2          1   1.59369  0.733239
273  Aston Villa          Tottenham          0          4   1.23267   2.25381
274     Brighton  Nottingham Forest          1          0  0.534518  0.687034
275     West Ham            Burnley          2          2   1.87414   0.88131
276    Liverpool    Manchester City          1          1   2.25492   1.37289

[277 rows x 6 columns]